"""Replay expert trajectory data on the XLEO dual hand scene.

Loads a pkl file generated by generate_massage_data.py and drives the
simulation using PD torque control for all joints. Records the actual
joint positions/velocities during replay, detects contact between hand
and arm to synthesise smooth (half-sine) contact force reference curves,
then saves the recorded data as a new pkl for imitation learning.

Usage:
    python replay_massage.py --pkl_path massage_data.pkl
    python replay_massage.py --pkl_path massage_data.pkl --output replay.pkl
    python replay_massage.py --pkl_path massage_data.pkl --headless
"""

import argparse
import pickle
import signal
from dataclasses import asdict, dataclass, fields
from pathlib import Path

import mujoco
import mujoco.viewer
import numpy as np

from mujoco_playground._src.manipulation.xleo_hand import constants as consts


def _project_root() -> Path:
  """Walk up from this file to find the project root (directory containing .git)."""
  p = Path(__file__).resolve().parent
  while p != p.parent:
    if (p / ".git").exists():
      return p
    p = p.parent
  raise RuntimeError("Cannot find project root (no .git found)")


# ---------------------------------------------------------------------------
# Config
# ---------------------------------------------------------------------------


@dataclass
class ReplayConfig:
  # PD gains
  wrist_kp: float = 50
  wrist_kd: float = 5
  wrist_rot_kp: float = 10.0
  wrist_rot_kd: float = 0.5
  finger_kp: float = 5.0
  finger_kd: float = 0.1
  # Contact force synthesis: peak force per axis (N)
  # -- Left wrist --
  l_wrist_fx: float = 0
  l_wrist_fy: float = 1.5
  # -- Left fingers --
  l_f0_fx: float = -1.5
  l_f0_fy: float = 0.5
  l_f1_fx: float = 1.5
  l_f1_fy: float = 1.0
  l_f2_fx: float = 0.8
  l_f2_fy: float = 1.2
  # -- Right wrist --
  r_wrist_fx: float = 0
  r_wrist_fy: float = -1.5
  # -- Right fingers --
  r_f0_fx: float = -1.5
  r_f0_fy: float = -0.5
  r_f1_fx: float = 1.5
  r_f1_fy: float = -1.0
  r_f2_fx: float = 0.8
  r_f2_fy: float = -1.2


# ---------------------------------------------------------------------------
# Contact detection helpers
# ---------------------------------------------------------------------------


def _detect_contact_cfrc_ext(data, body_ids, threshold=0.01):
  """Detect external contact on bodies using cfrc_ext.

  cfrc_ext is the pure external contact force (no gravity) at each body's CoM,
  expressed in the world frame.  Shape: (nbody, 6) where [:3] = torque, [3:] = force.

  Returns:
    contact: bool array (n_bodies,) — True if |force| > threshold.
  """
  n_bodies = len(body_ids)
  contact = np.zeros(n_bodies, dtype=bool)
  for i, body_id in enumerate(body_ids):
    force = data.cfrc_ext[body_id, 3:]
    if np.linalg.norm(force) > threshold:
      contact[i] = True
  return contact


def _synthesise_contact_force(
    contact_mask: np.ndarray,
    f_max_xy: np.ndarray,
) -> np.ndarray:
  """Synthesise smooth half-sine contact force curves from contact detection.

  For each body, finds the **first** and **last** contact frame across the
  entire trajectory, then fills [first, last] with a single half-sine envelope.
  X and Y peak amplitudes are specified per body; Z is always 0.

  Args:
    contact_mask: (T, n_bodies) bool array of per-step contact flags.
    f_max_xy: (n_bodies, 2) peak force [fx, fy] for each body (N).

  Returns:
    contact_force: (T, n_bodies, 3) smooth force vectors (fz = 0).
  """
  T, n_bodies = contact_mask.shape
  contact_force = np.zeros((T, n_bodies, 3))

  for b in range(n_bodies):
    mask = contact_mask[:, b]
    contact_indices = np.where(mask)[0]
    if len(contact_indices) == 0:
      continue

    t_first = int(contact_indices[0])
    t_last = int(contact_indices[-1])
    length = t_last - t_first
    if length == 0:
      continue

    # Single half-sine envelope from t_first to t_last.
    t_range = np.arange(t_first, t_last + 1)
    phase = (t_range - t_first) / length  # 0 → 1
    sine = np.sin(np.pi * phase)

    contact_force[t_range, b, 0] = f_max_xy[b, 0] * sine  # fx
    contact_force[t_range, b, 1] = f_max_xy[b, 1] * sine  # fy
    # fz stays 0

  return contact_force


# ---------------------------------------------------------------------------
# Main replay loop
# ---------------------------------------------------------------------------


def run(
    pkl_path: str,
    cfg: ReplayConfig,
    output: str,
    headless: bool,
):
  with open(pkl_path, "rb") as f:
    traj = pickle.load(f)

  qpos_data = traj["qpos"]  # (T, NQ)
  src_data_freq = traj["data_freq"]
  duration = traj["duration"]

  scene_xml = str(
      _project_root()
      / "mujoco_playground"
      / "_src"
      / "manipulation"
      / "xleo_hand"
      / "models"
      / "xmls"
      / "ftl_xleo_dual_hand.scene.xml"
  )
  model = mujoco.MjModel.from_xml_path(scene_xml)

  # Override timestep to match source data frequency so simulation runs at
  # the same rate as the recorded data – no interpolation or downsampling needed.
  model.opt.timestep = 1.0 / src_data_freq
  data = mujoco.MjData(model)

  # Resolve actuator ctrl indices and joint qpos/qvel addresses.
  act_ids = [model.actuator(n).id for n in consts.ACTUATOR_NAMES]
  qpos_adrs = []
  qvel_adrs = []
  for jname in consts.JOINT_NAMES:
    jid = model.joint(jname).id
    qpos_adrs.append(model.jnt_qposadr[jid])
    qvel_adrs.append(model.jnt_dofadr[jid])

  # Resolve body ids for tracked body xpos and key body xpos.
  tracked_body_ids = [model.body(n).id for n in consts.TRACKED_BODY_NAMES]
  key_body_ids = [model.body(n).id for n in consts.KEY_BODY_NAMES]

  # Wrist body IDs for coordinate transformation.
  l_wrist_body_id = model.body("L_WRIST").id
  r_wrist_body_id = model.body("R_WRIST").id

  # Index mapping within TRACKED_BODY_NAMES (20 bodies):
  #   LEFT_BODY_NAMES:  [0]=L_WRIST, [1..9]=left finger bodies
  #   RIGHT_BODY_NAMES: [10]=R_WRIST, [11..19]=right finger bodies
  n_left = len(consts.LEFT_BODY_NAMES)  # 10
  left_wrist_idx = 0
  right_wrist_idx = n_left  # 10
  left_finger_slice = slice(1, n_left)  # 1..9
  right_finger_slice = slice(
      n_left + 1, len(consts.TRACKED_BODY_NAMES)
  )  # 11..19

  # KEY_BODY_NAMES: first N are left, rest are right.
  n_left_key = len([n for n in consts.KEY_BODY_NAMES if "_L" in n])

  # --- Contact detection setup (cfrc_ext on CONTACT_FORCE_BODY_NAMES) ---
  contact_body_ids = [model.body(n).id for n in consts.CONTACT_FORCE_BODY_NAMES]
  n_contact_bodies = len(consts.CONTACT_FORCE_BODY_NAMES)
  print(f"Contact bodies: {list(consts.CONTACT_FORCE_BODY_NAMES)}")

  # Per-joint kp/kd: wrist slide vs wrist hinge vs finger gains.
  kp = np.zeros(consts.NQ)
  kd = np.zeros(consts.NQ)
  kp[consts.WRIST_SLIDE_INDICES] = cfg.wrist_kp
  kd[consts.WRIST_SLIDE_INDICES] = cfg.wrist_kd
  kp[consts.WRIST_HINGE_INDICES] = cfg.wrist_rot_kp
  kd[consts.WRIST_HINGE_INDICES] = cfg.wrist_rot_kd
  kp[consts.FINGER_INDICES] = cfg.finger_kp
  kd[consts.FINGER_INDICES] = cfg.finger_kd

  # Per-body f_max (fx, fy): each body maps to its own config pair.
  # CONTACT_FORCE_BODY_NAMES order:
  #   L_WRIST, LINK_F0_L2, LINK_F1_L1, LINK_F2_L1,
  #   R_WRIST, LINK_F0_R2, LINK_F1_R1, LINK_F2_R1
  _body_force_map = {
      "L_WRIST": (cfg.l_wrist_fx, cfg.l_wrist_fy),
      "LINK_F0_L2": (cfg.l_f0_fx, cfg.l_f0_fy),
      "LINK_F1_L1": (cfg.l_f1_fx, cfg.l_f1_fy),
      "LINK_F2_L1": (cfg.l_f2_fx, cfg.l_f2_fy),
      "R_WRIST": (cfg.r_wrist_fx, cfg.r_wrist_fy),
      "LINK_F0_R2": (cfg.r_f0_fx, cfg.r_f0_fy),
      "LINK_F1_R1": (cfg.r_f1_fx, cfg.r_f1_fy),
      "LINK_F2_R1": (cfg.r_f2_fx, cfg.r_f2_fy),
  }
  f_max_xy = np.array(
      [list(_body_force_map[n]) for n in consts.CONTACT_FORCE_BODY_NAMES]
  )

  # Simulation loop parameters – timestep already set to 1/src_data_freq,
  # so each simulation step corresponds to exactly one data frame.
  timestep = model.opt.timestep
  total_steps = int(duration / timestep)

  print(
      f"Simulation: timestep={timestep}, total_steps={total_steps}, "
      f"record every step, data_freq={src_data_freq} Hz (same as source)"
  )
  print(f"Duration: {duration}s, source data_freq: {src_data_freq} Hz")

  # Storage for recorded data.
  rec_qpos = []
  rec_qvel = []
  rec_tracked_body_xpos = []
  rec_key_body_xpos = []
  # Contact detection storage (raw per-step).
  contact_mask_list = []
  cfrc_ext_raw_list = []

  for step_i in range(total_steps):
    # Direct index into data – each step corresponds to one data frame.
    data_idx = step_i % qpos_data.shape[0]
    qpos_target = qpos_data[data_idx]

    # PD torque control.
    for i in range(consts.NQ):
      q_err = qpos_target[i] - data.qpos[qpos_adrs[i]]
      qvel_actual = data.qvel[qvel_adrs[i]]
      torque = kp[i] * q_err - kd[i] * qvel_actual
      data.ctrl[act_ids[i]] = torque

    # Step physics.
    mujoco.mj_step(model, data)

    # Record every step (sim freq == data freq, no downsampling).
    rec_qpos.append(np.array([data.qpos[a] for a in qpos_adrs]))
    rec_qvel.append(np.array([data.qvel[a] for a in qvel_adrs]))

    # Detect contact using cfrc_ext (pure external force, no gravity).
    contact = _detect_contact_cfrc_ext(data, contact_body_ids)
    contact_mask_list.append(contact)
    # Record raw cfrc_ext linear force (world frame) for plotting only.
    cfrc_ext_raw_list.append(
        np.array([data.cfrc_ext[b, 3:].copy() for b in contact_body_ids])
    )

    # Record tracked body xpos: wrist in world frame, fingers in wrist-local frame.
    all_xpos = np.array([data.xpos[b].copy() for b in tracked_body_ids])
    l_wrist_pos = data.xpos[l_wrist_body_id].copy()
    r_wrist_pos = data.xpos[r_wrist_body_id].copy()
    l_wrist_rot = data.xmat[l_wrist_body_id].reshape(3, 3)
    r_wrist_rot = data.xmat[r_wrist_body_id].reshape(3, 3)

    tracked_frame = np.empty_like(all_xpos)
    tracked_frame[left_wrist_idx] = l_wrist_pos
    tracked_frame[right_wrist_idx] = r_wrist_pos
    tracked_frame[left_finger_slice] = (
        all_xpos[left_finger_slice] - l_wrist_pos
    ) @ l_wrist_rot
    tracked_frame[right_finger_slice] = (
        all_xpos[right_finger_slice] - r_wrist_pos
    ) @ r_wrist_rot
    rec_tracked_body_xpos.append(tracked_frame)

    # Record key body xpos (fingertips) in wrist-local frame.
    all_key_xpos = np.array([data.xpos[b].copy() for b in key_body_ids])
    key_frame = np.empty_like(all_key_xpos)
    key_frame[:n_left_key] = (
        all_key_xpos[:n_left_key] - l_wrist_pos
    ) @ l_wrist_rot
    key_frame[n_left_key:] = (
        all_key_xpos[n_left_key:] - r_wrist_pos
    ) @ r_wrist_rot
    rec_key_body_xpos.append(key_frame)

    # Progress.
    if step_i % (total_steps // 10) == 0:
      pct = step_i / total_steps * 100
      print(f"  {pct:.0f}% ({step_i}/{total_steps})")

  rec_qpos = np.array(rec_qpos)  # (T, NQ)
  rec_qvel = np.array(rec_qvel)  # (T, NQ)
  rec_tracked_body_xpos = np.array(rec_tracked_body_xpos)  # (T, 20, 3)
  rec_key_body_xpos = np.array(rec_key_body_xpos)  # (T, 6, 3)

  # --- Synthesise smooth contact force reference ---
  contact_mask = np.array(contact_mask_list)  # (T, n_bodies)

  # Print contact detection summary.
  print("\n--- Contact detection summary ---")
  for b_idx, b_name in enumerate(consts.CONTACT_FORCE_BODY_NAMES):
    n_contact = contact_mask[:, b_idx].sum()
    print(f"  {b_name}: {n_contact}/{total_steps} frames in contact")

  rec_tracked_contact_force = _synthesise_contact_force(contact_mask, f_max_xy)
  print(f"\nSynthesised contact force: {rec_tracked_contact_force.shape}")

  # Raw cfrc_ext for plotting only (not saved to output pkl).
  rec_cfrc_ext_raw = np.array(cfrc_ext_raw_list)  # (T, n_bodies, 3)

  # Check cyclic trajectory condition: first frame vs last frame.
  print("\n--- Cyclic trajectory check (|first - last| per joint) ---")
  diff = np.abs(rec_qpos[0] - rec_qpos[-1])
  for i, jname in enumerate(consts.JOINT_NAMES):
    status = "OK" if diff[i] < 0.01 else "WARN"
    print(f"  [{status}] {jname}: diff={diff[i]:.6f}")

  print(
      f"\nRecorded: qpos {rec_qpos.shape}, qvel {rec_qvel.shape}, "
      f"contact_force {rec_tracked_contact_force.shape}, "
      f"tracked_body_xpos {rec_tracked_body_xpos.shape}, "
      f"key_body_xpos {rec_key_body_xpos.shape}"
  )

  # Save recorded data (cfrc_ext_raw not included — only for plotting).
  output_data = {
      "qpos": rec_qpos,
      "qvel": rec_qvel,
      "tracked_contact_force": rec_tracked_contact_force,
      "contact_body_names": list(consts.CONTACT_FORCE_BODY_NAMES),
      "tracked_body_xpos": rec_tracked_body_xpos,
      "key_body_xpos": rec_key_body_xpos,
      "tracked_body_names": list(consts.TRACKED_BODY_NAMES),
      "key_body_names": list(consts.KEY_BODY_NAMES),
      "data_freq": src_data_freq,
      "duration": duration,
  }

  Path(output).parent.mkdir(parents=True, exist_ok=True)
  with open(output, "wb") as f:
    pickle.dump(output_data, f)
  print(f"Saved to {output}")

  # Plot all recorded data (include cfrc_ext_raw for plotting only).
  plot_dir = Path(output).parent / "plots"
  print(f"Plotting replay data to {plot_dir} ...")
  from mujoco_playground._src.manipulation.xleo_hand.tools.plot_utils import plot_all

  plot_data = dict(output_data)
  plot_data["cfrc_ext_raw"] = rec_cfrc_ext_raw
  freq = src_data_freq
  plot_all(plot_data, plot_dir, prefix=f"{int(freq)}hz_replay_")

  # Optionally launch viewer for visual inspection (non-headless mode).
  if not headless:
    print("Launching viewer for visual inspection (Ctrl+C to exit)...")

    def controller(m, d):
      # Compute data frame index from simulation time.
      data_idx = int(d.time * src_data_freq) % qpos_data.shape[0]
      qpos_target = qpos_data[data_idx]
      for i in range(consts.NQ):
        q_err = qpos_target[i] - d.qpos[qpos_adrs[i]]
        qvel_actual = d.qvel[qvel_adrs[i]]
        torque = kp[i] * q_err - kd[i] * qvel_actual
        d.ctrl[act_ids[i]] = torque

    # Reset data for viewer playback.
    data2 = mujoco.MjData(model)
    mujoco.set_mjcb_control(controller)
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    mujoco.viewer.launch(model, data2)


def main():
  parser = argparse.ArgumentParser(
      description="Replay massage expert trajectory and record simulation data"
  )
  default_pkl = str(_project_root() / "data" / "massage_data.pkl")
  default_output = str(_project_root() / "data" / "massage_replay_data.pkl")
  parser.add_argument(
      "--pkl_path",
      type=str,
      default=default_pkl,
      help="Path to trajectory pkl (default: data/massage_data.pkl)",
  )
  parser.add_argument(
      "--output",
      type=str,
      default=default_output,
      help="Output pkl path (default: data/massage_replay_data.pkl)",
  )
  parser.add_argument(
      "--headless",
      action="store_true",
      default=False,
      help="Headless mode: record without viewer (default: False)",
  )
  parser.add_argument(
      "--no-headless",
      dest="headless",
      action="store_false",
      help="Disable headless mode: launch viewer after recording",
  )
  # ReplayConfig fields as CLI args.
  for f in fields(ReplayConfig):
    parser.add_argument(
        f"--{f.name}",
        type=float,
        default=f.default,
        help=f"{f.name} (default: {f.default})",
    )
  args = parser.parse_args()
  cfg = ReplayConfig(
      **{f.name: getattr(args, f.name) for f in fields(ReplayConfig)}
  )
  run(args.pkl_path, cfg, args.output, args.headless)


if __name__ == "__main__":
  main()
