"""Replay expert trajectory data on the XLEO dual hand scene.

Loads a pkl file generated by generate_massage_data.py and drives the
simulation using PD torque control for all joints.

Usage:
    python replay_massage.py --pkl_path massage_data.pkl
    python replay_massage.py --pkl_path massage_data.pkl --finger_kp 8.0
"""

import argparse
import pickle
import signal
from pathlib import Path

import mujoco
import mujoco.viewer
import numpy as np


def _project_root() -> Path:
  """Walk up from this file to find the project root (directory containing .git)."""
  p = Path(__file__).resolve().parent
  while p != p.parent:
    if (p / ".git").exists():
      return p
    p = p.parent
  raise RuntimeError("Cannot find project root (no .git found)")


# All 30 actuator names (same order as joint indices 0..29)
ACTUATOR_NAMES = [
    # Left wrist (6)
    "M_LINK_HAND_BASE_L_X",
    "M_LINK_HAND_BASE_L_Y",
    "M_LINK_HAND_BASE_L_Z",
    "M_LINK_HAND_BASE_L_ROLL",
    "M_LINK_HAND_BASE_L_PITCH",
    "M_LINK_HAND_BASE_L_YAW",
    # Left fingers (9)
    "M_F0_L0",
    "M_F0_L1",
    "M_F0_L2",
    "M_F1_L0",
    "M_F1_L1",
    "M_F1_L2",
    "M_F2_L0",
    "M_F2_L1",
    "M_F2_L2",
    # Right wrist (6)
    "M_LINK_HAND_BASE_R_X",
    "M_LINK_HAND_BASE_R_Y",
    "M_LINK_HAND_BASE_R_Z",
    "M_LINK_HAND_BASE_R_ROLL",
    "M_LINK_HAND_BASE_R_PITCH",
    "M_LINK_HAND_BASE_R_YAW",
    # Right fingers (9)
    "M_F0_R0",
    "M_F0_R1",
    "M_F0_R2",
    "M_F1_R0",
    "M_F1_R1",
    "M_F1_R2",
    "M_F2_R0",
    "M_F2_R1",
    "M_F2_R2",
]

JOINT_NAMES = [
    # Left wrist (6)
    "J_LINK_HAND_BASE_L_X",
    "J_LINK_HAND_BASE_L_Y",
    "J_LINK_HAND_BASE_L_Z",
    "J_LINK_HAND_BASE_L_ROLL",
    "J_LINK_HAND_BASE_L_PITCH",
    "J_LINK_HAND_BASE_L_YAW",
    # Left fingers (9)
    "J_F0_L0",
    "J_F0_L1",
    "J_F0_L2",
    "J_F1_L0",
    "J_F1_L1",
    "J_F1_L2",
    "J_F2_L0",
    "J_F2_L1",
    "J_F2_L2",
    # Right wrist (6)
    "J_LINK_HAND_BASE_R_X",
    "J_LINK_HAND_BASE_R_Y",
    "J_LINK_HAND_BASE_R_Z",
    "J_LINK_HAND_BASE_R_ROLL",
    "J_LINK_HAND_BASE_R_PITCH",
    "J_LINK_HAND_BASE_R_YAW",
    # Right fingers (9)
    "J_F0_R0",
    "J_F0_R1",
    "J_F0_R2",
    "J_F1_R0",
    "J_F1_R1",
    "J_F1_R2",
    "J_F2_R0",
    "J_F2_R1",
    "J_F2_R2",
]


def _interpolate(data: np.ndarray, t: float, data_freq: float) -> np.ndarray:
  """Linearly interpolate a (T, D) array at continuous time t."""
  idx = t * data_freq
  T = data.shape[0]
  i0 = int(idx)
  if i0 >= T - 1:
    return data[-1]
  i1 = i0 + 1
  alpha = idx - i0
  return (1.0 - alpha) * data[i0] + alpha * data[i1]


def run(
    pkl_path: str,
    wrist_kp: float,
    wrist_kd: float,
    finger_kp: float,
    finger_kd: float,
):
  with open(pkl_path, "rb") as f:
    traj = pickle.load(f)

  qpos_data = traj["qpos"]  # (T, 30)
  data_freq = traj["data_freq"]
  duration = traj["duration"]

  scene_xml = str(
      _project_root()
      / "mujoco_playground"
      / "_src"
      / "manipulation"
      / "xleo_hand"
      / "models"
      / "xmls"
      / "ftl_xleo_dual_hand.scene.xml"
  )
  model = mujoco.MjModel.from_xml_path(scene_xml)
  data = mujoco.MjData(model)

  # Resolve actuator ctrl indices and joint qpos/qvel addresses.
  act_ids = [model.actuator(n).id for n in ACTUATOR_NAMES]
  qpos_adrs = []
  qvel_adrs = []
  for jname in JOINT_NAMES:
    jid = model.joint(jname).id
    qpos_adrs.append(model.jnt_qposadr[jid])
    qvel_adrs.append(model.jnt_dofadr[jid])

  # Per-joint kp/kd: wrist (0..5, 15..20), fingers (6..14, 21..29).
  kp = np.zeros(30)
  kd = np.zeros(30)
  wrist_indices = list(range(0, 6)) + list(range(15, 21))
  finger_indices = list(range(6, 15)) + list(range(21, 30))
  kp[wrist_indices] = wrist_kp
  kd[wrist_indices] = wrist_kd
  kp[finger_indices] = finger_kp
  kd[finger_indices] = finger_kd

  def controller(m, d):
    """PD torque control for all joints."""
    t = d.time % duration
    qpos_target = _interpolate(qpos_data, t, data_freq)

    for i in range(30):
      q_err = qpos_target[i] - d.qpos[qpos_adrs[i]]
      qvel_actual = d.qvel[qvel_adrs[i]]
      torque = kp[i] * q_err - kd[i] * qvel_actual
      d.ctrl[act_ids[i]] = torque

  mujoco.set_mjcb_control(controller)
  signal.signal(signal.SIGINT, signal.SIG_DFL)
  mujoco.viewer.launch(model, data)


def main():
  parser = argparse.ArgumentParser(
      description="Replay massage expert trajectory"
  )
  default_pkl = str(_project_root() / "data" / "massage_data.pkl")
  parser.add_argument(
      "--pkl_path",
      type=str,
      default=default_pkl,
      help="Path to trajectory pkl (default: data/massage_data.pkl)",
  )
  parser.add_argument(
      "--wrist_kp",
      type=float,
      default=100.0,
      help="Wrist PD kp (default: 100.0)",
  )
  parser.add_argument(
      "--wrist_kd", type=float, default=5.0, help="Wrist PD kd (default: 5.0)"
  )
  parser.add_argument(
      "--finger_kp", type=float, default=5.0, help="Finger PD kp (default: 5.0)"
  )
  parser.add_argument(
      "--finger_kd", type=float, default=0.1, help="Finger PD kd (default: 0.1)"
  )
  args = parser.parse_args()
  run(
      args.pkl_path,
      args.wrist_kp,
      args.wrist_kd,
      args.finger_kp,
      args.finger_kd,
  )


if __name__ == "__main__":
  main()
