"""Replay expert trajectory data on the XLEO dual hand scene.

Loads a pkl file generated by generate_massage_data.py and drives the
simulation using linear interpolation to align data timestamps with the
MuJoCo control timestep.

Usage:
    python replay_massage.py --pkl_path massage_data.pkl
    python replay_massage.py --pkl_path massage_data.pkl --finger_kp 8.0
"""

import argparse
import pickle
import signal
from pathlib import Path

import mujoco
import mujoco.viewer
import numpy as np


def _project_root() -> Path:
    """Walk up from this file to find the project root (directory containing .git)."""
    p = Path(__file__).resolve().parent
    while p != p.parent:
        if (p / ".git").exists():
            return p
        p = p.parent
    raise RuntimeError("Cannot find project root (no .git found)")


# 12 position actuators (wrist 6×2)
WRIST_ACTUATOR_NAMES = [
    "M_LINK_HAND_BASE_L_X", "M_LINK_HAND_BASE_L_Y", "M_LINK_HAND_BASE_L_Z",
    "M_LINK_HAND_BASE_L_ROLL", "M_LINK_HAND_BASE_L_PITCH", "M_LINK_HAND_BASE_L_YAW",
    "M_LINK_HAND_BASE_R_X", "M_LINK_HAND_BASE_R_Y", "M_LINK_HAND_BASE_R_Z",
    "M_LINK_HAND_BASE_R_ROLL", "M_LINK_HAND_BASE_R_PITCH", "M_LINK_HAND_BASE_R_YAW",
]
# Corresponding joint indices in the 30-joint vector (0..14 left, 15..29 right)
WRIST_JOINT_INDICES = [0, 1, 2, 3, 4, 5, 15, 16, 17, 18, 19, 20]

# 18 motor actuators (finger 9×2) and their joint indices
FINGER_ACTUATOR_NAMES = [
    "M_F0_L0", "M_F0_L1", "M_F0_L2",
    "M_F1_L0", "M_F1_L1", "M_F1_L2",
    "M_F2_L0", "M_F2_L1", "M_F2_L2",
    "M_F0_R0", "M_F0_R1", "M_F0_R2",
    "M_F1_R0", "M_F1_R1", "M_F1_R2",
    "M_F2_R0", "M_F2_R1", "M_F2_R2",
]
FINGER_JOINT_INDICES = [6, 7, 8, 9, 10, 11, 12, 13, 14, 21, 22, 23, 24, 25, 26, 27, 28, 29]

# Joint names matching the index order (for resolving qpos/qvel addresses)
FINGER_JOINT_NAMES = [
    "J_F0_L0", "J_F0_L1", "J_F0_L2",
    "J_F1_L0", "J_F1_L1", "J_F1_L2",
    "J_F2_L0", "J_F2_L1", "J_F2_L2",
    "J_F0_R0", "J_F0_R1", "J_F0_R2",
    "J_F1_R0", "J_F1_R1", "J_F1_R2",
    "J_F2_R0", "J_F2_R1", "J_F2_R2",
]


def _interpolate(data: np.ndarray, t: float, data_freq: float) -> np.ndarray:
    """Linearly interpolate a (T, D) array at continuous time t."""
    idx = t * data_freq
    T = data.shape[0]
    i0 = int(idx)
    if i0 >= T - 1:
        return data[-1]
    i1 = i0 + 1
    alpha = idx - i0
    return (1.0 - alpha) * data[i0] + alpha * data[i1]


def run(pkl_path: str, finger_kp: float, finger_kd: float):
    with open(pkl_path, "rb") as f:
        traj = pickle.load(f)

    qpos_data = traj["qpos"]  # (T, 30)
    qvel_data = traj["qvel"]  # (T, 30)
    data_freq = traj["data_freq"]
    duration = traj["duration"]

    scene_xml = str(
        _project_root() / "mujoco_playground" / "_src" / "manipulation"
        / "xleo_hand" / "models" / "xmls" / "ftl_xleo_dual_hand.scene.xml"
    )
    model = mujoco.MjModel.from_xml_path(scene_xml)
    data = mujoco.MjData(model)

    # Resolve wrist actuator ctrl indices
    wrist_act_ids = [model.actuator(n).id for n in WRIST_ACTUATOR_NAMES]

    # Resolve finger actuator ctrl indices and joint addresses
    finger_act_ids = [model.actuator(n).id for n in FINGER_ACTUATOR_NAMES]
    finger_qpos_adrs = []
    finger_qvel_adrs = []
    for jname in FINGER_JOINT_NAMES:
        jid = model.joint(jname).id
        finger_qpos_adrs.append(model.jnt_qposadr[jid])
        finger_qvel_adrs.append(model.jnt_dofadr[jid])

    def controller(m, d):
        """Called via mjcb_control before each mj_step."""
        t = d.time % duration
        qpos_target = _interpolate(qpos_data, t, data_freq)

        # Wrist position actuators: set ctrl = target qpos
        for i, act_id in enumerate(wrist_act_ids):
            joint_idx = WRIST_JOINT_INDICES[i]
            d.ctrl[act_id] = qpos_target[joint_idx]

        # Finger motor actuators: PD torque control
        for i, act_id in enumerate(finger_act_ids):
            joint_idx = FINGER_JOINT_INDICES[i]
            qpos_actual = d.qpos[finger_qpos_adrs[i]]
            qvel_actual = d.qvel[finger_qvel_adrs[i]]
            torque = finger_kp * (qpos_target[joint_idx] - qpos_actual) - finger_kd * qvel_actual
            d.ctrl[act_id] = torque

    mujoco.set_mjcb_control(controller)
    signal.signal(signal.SIGINT, signal.SIG_DFL)
    mujoco.viewer.launch(model, data)


def main():
    parser = argparse.ArgumentParser(description="Replay massage expert trajectory")
    default_pkl = str(_project_root() / "data" / "massage_data.pkl")
    parser.add_argument("--pkl_path", type=str, default=default_pkl, help="Path to trajectory pkl (default: data/massage_data.pkl)")
    parser.add_argument("--finger_kp", type=float, default=5.0, help="Finger PD kp (default: 5.0)")
    parser.add_argument("--finger_kd", type=float, default=0.1, help="Finger PD kd (default: 0.1)")
    args = parser.parse_args()
    run(args.pkl_path, args.finger_kp, args.finger_kd)


if __name__ == "__main__":
    main()
