"""Resample massage trajectory data from source frequency to target frequency.

Reads the raw massage_data.pkl (generated by generate_massage_data.py at
data_freq, e.g. 120 Hz) and resamples all trajectory arrays (qpos, qvel,
tracked_body_xpos, key_body_xpos) to a target frequency (default 100 Hz)
via linear interpolation. The resampled pkl can be loaded directly by
massage.py without any runtime resampling.

After resampling, plots each data field and saves the figures next to the
output pkl.

Usage:
    python resample_massage_data.py
    python resample_massage_data.py --target_freq 100.0
    python resample_massage_data.py --input raw.pkl --output resampled.pkl
"""

import argparse
import pickle
from pathlib import Path

import numpy as np


def _project_root() -> Path:
  """Walk up from this file to find the project root (directory containing .git)."""
  p = Path(__file__).resolve().parent
  while p != p.parent:
    if (p / ".git").exists():
      return p
    p = p.parent
  raise RuntimeError("Cannot find project root (no .git found)")


def _resample_2d(
    src: np.ndarray, src_times: np.ndarray, dst_times: np.ndarray
) -> np.ndarray:
  """Resample (T_src, D) array to (T_dst, D) via per-column linear interp."""
  return np.stack(
      [np.interp(dst_times, src_times, src[:, j]) for j in range(src.shape[1])],
      axis=1,
  )


def _resample_3d(
    src: np.ndarray, src_times: np.ndarray, dst_times: np.ndarray
) -> np.ndarray:
  """Resample (T_src, N, 3) array to (T_dst, N, 3) via linear interp."""
  T_dst = len(dst_times)
  out = np.zeros((T_dst, src.shape[1], src.shape[2]))
  for b in range(src.shape[1]):
    for d in range(src.shape[2]):
      out[:, b, d] = np.interp(dst_times, src_times, src[:, b, d])
  return out


def resample(data: dict, target_freq: float) -> dict:
  """Resample all trajectory arrays from data_freq to target_freq.

  Args:
    data: dict from generate_massage_data.py with keys qpos, qvel,
          tracked_body_xpos, key_body_xpos, data_freq, duration, etc.
    target_freq: target sampling frequency in Hz.

  Returns:
    New dict with resampled arrays and updated data_freq.
  """
  src_freq = float(data["data_freq"])
  duration = float(data["duration"])

  if abs(src_freq - target_freq) < 1e-6:
    print(f"Source freq ({src_freq} Hz) == target freq, no resampling needed.")
    return data

  src_len = data["qpos"].shape[0]
  dst_len = int(round(duration * target_freq))
  src_times = np.arange(src_len) / src_freq
  dst_times = np.arange(dst_len) / target_freq

  print(
      f"Resampling: {src_freq} Hz ({src_len} frames) -> "
      f"{target_freq} Hz ({dst_len} frames), duration={duration}s"
  )

  result = dict(data)  # shallow copy
  result["qpos"] = _resample_2d(np.array(data["qpos"]), src_times, dst_times)
  result["qvel"] = _resample_2d(np.array(data["qvel"]), src_times, dst_times)

  if "tracked_body_xpos" in data:
    result["tracked_body_xpos"] = _resample_3d(
        np.array(data["tracked_body_xpos"]), src_times, dst_times
    )
  if "key_body_xpos" in data:
    result["key_body_xpos"] = _resample_3d(
        np.array(data["key_body_xpos"]), src_times, dst_times
    )

  if "tracked_contact_force" in data:
    result["tracked_contact_force"] = _resample_3d(
        np.array(data["tracked_contact_force"]), src_times, dst_times
    )

  # Pass through string fields that don't need resampling.
  for name_key in ("contact_sensor_names", "contact_body_names"):
    if name_key in data:
      result[name_key] = data[name_key]

  result["data_freq"] = target_freq
  return result


def main():
  data_dir = _project_root() / "data"
  default_input = data_dir / "massage_replay_data.pkl"
  default_output = data_dir / "massage_traj.pkl"
  parser = argparse.ArgumentParser(
      description="Resample massage trajectory data to target frequency"
  )
  parser.add_argument(
      "--input",
      type=str,
      default=str(default_input),
      help="Input pkl path (default: data/massage_replay_data.pkl)",
  )
  parser.add_argument(
      "--output",
      type=str,
      default=str(default_output),
      help="Output pkl path (default: data/massage_traj.pkl)",
  )
  parser.add_argument(
      "--target_freq",
      type=float,
      default=50.0,
      help="Target sampling frequency in Hz (default: 100.0)",
  )
  parser.add_argument(
      "--no_plot",
      action="store_true",
      default=False,
      help="Skip plotting (default: False)",
  )
  args = parser.parse_args()
  output = args.output

  with open(args.input, "rb") as f:
    data = pickle.load(f)

  print(
      f"Loaded {args.input}: {data['qpos'].shape[0]} frames, "
      f"{data['data_freq']} Hz, {data['duration']}s"
  )

  data = resample(data, args.target_freq)

  with open(output, "wb") as f:
    pickle.dump(data, f)

  print(
      f"Saved {output}: {data['qpos'].shape[0]} frames, {data['data_freq']} Hz"
  )
  for key in [
      "qpos",
      "qvel",
      "tracked_body_xpos",
      "key_body_xpos",
      "tracked_contact_force",
  ]:
    if key in data:
      print(f"  {key}: {data[key].shape}")

  # Plot all data fields.
  if not args.no_plot:
    plot_dir = Path(output).parent / "plots"
    plot_dir.mkdir(parents=True, exist_ok=True)
    from mujoco_playground._src.manipulation.xleo_hand.tools.plot_utils import plot_all

    freq = data["data_freq"]
    plot_all(data, plot_dir, prefix=f"{int(freq)}hz_resampled_")
    print(f"All plots saved to {plot_dir}/")


if __name__ == "__main__":
  main()
